package com.example.bookshop.data.entity;

import com.example.bookshop.data.entity.Author;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.persistence.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "books")
@Schema(description = "entity representing a book")
public class Book {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "id generated by DB automatically")
    private Integer id;
    @ManyToOne
    @JoinColumn(name = "author_id", referencedColumnName = "id")
    @JsonIgnore
    private Author author;

    @OneToMany(mappedBy = "book")
    private List<BookFile> bookFileList = new ArrayList<>();

    /*@ManyToMany(mappedBy = "tagBooks")
    @JsonIgnore
    private Set<Tag> tags;*/
    @Schema(description = "book title")
    private String title;
    @Schema(description = "date of book publication")
    private LocalDate pubDate;
    @Column(name = "is_bestseller")
    @Schema(description = "if isBestSeller = 1 so the book is considered to be bestseller, if isBestSeller = 0, the book is not bestseller")
    private Integer isBestSeller;
    @Schema(description = "mnemonic identity sequence of characters")
    private String slug;
    @Schema(description = "image url")
    private String image;
    @Schema(description = "book description text")
    private String description;
    @Schema(description = "book price without discount")
    private Integer price;
    @Schema(description = "discount value for book in percent")
    private Integer discount;

    @JsonProperty
    public Double discountPrice() {
        return Math.floor(((price * ((100.0 - discount) / 100.0)) / 100.0)*100)/100;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Author getAuthor() {
        return author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public LocalDate getPubDate() {
        return pubDate;
    }

    public void setPubDate(LocalDate pubDate) {
        this.pubDate = pubDate;
    }

    public Integer getIsBestSeller() {
        return isBestSeller;
    }

    public void setIsBestSeller(Integer bestSeller) {
        this.isBestSeller = bestSeller;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public Integer getDiscount() {
        return discount;
    }

    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    public List<BookFile> getBookFileList() {
        return bookFileList;
    }

    public void setBookFileList(List<BookFile> bookFileList) {
        this.bookFileList = bookFileList;
    }
}
