insert into genres (id, parent_id, slug, name) values (1, 25, 'genre-slug-864-puv', 'Банковское дело');
insert into genres (id, parent_id, slug, name) values (2, null, 'genre-slug-742-tzv', 'Хобби, досуг ');
insert into genres (id, parent_id, slug, name) values (3, 25, 'genre-slug-526-jmv', 'Работа с клиентами');
insert into genres (id, parent_id, slug, name) values (4, 16, 'genre-slug-821-tso', 'Саморазвитие / личностный рост ');
insert into genres (id, parent_id, slug, name) values (5, 9, 'genre-slug-833-jmv', 'Биографии и мемуары');
insert into genres (id, parent_id, slug, name) values (6, 16, 'genre-slug-136-ohb', 'Путеводители');
insert into genres (id, parent_id, slug, name) values (7, 25, 'genre-slug-629-knt', 'Интернет-бизнес');
insert into genres (id, parent_id, slug, name) values (8, 25, 'genre-slug-329-ncd', 'Тайм-менеджмент');
insert into genres (id, parent_id, slug, name) values (9, null, 'genre-slug-645-mvf', 'Психология, мотивация ');
insert into genres (id, parent_id, slug, name) values (10, 16, 'genre-slug-350-qef', 'Хобби, досуг ');
insert into genres (id, parent_id, slug, name) values (11, 2, 'genre-slug-202-izb', 'Сад и огород');
insert into genres (id, parent_id, slug, name) values (12, 25, 'genre-slug-589-qwc', 'Переговоры');
insert into genres (id, parent_id, slug, name) values (13, 2, 'genre-slug-880-ksw', 'Йога');
insert into genres (id, parent_id, slug, name) values (14, 25, 'genre-slug-876-ikn', 'Продажи');
insert into genres (id, parent_id, slug, name) values (15, 25, 'genre-slug-494-klw', 'Менеджмент');
insert into genres (id, parent_id, slug, name) values (16, null, 'genre-slug-610-udn', 'Знания и навыки');
insert into genres (id, parent_id, slug, name) values (17, 2, 'genre-slug-773-cip', 'Интеллектуальные игры');
insert into genres (id, parent_id, slug, name) values (18, 2, 'genre-slug-011-ggn', 'Спорт / фитнес');
insert into genres (id, parent_id, slug, name) values (19, 2, 'genre-slug-201-jgq', 'Кулинария');
insert into genres (id, parent_id, slug, name) values (20, 16, 'genre-slug-967-jtm', 'Словари, справочники ');
insert into genres (id, parent_id, slug, name) values (21, 2, 'genre-slug-430-itp', 'Искусство фотографии');
insert into genres (id, parent_id, slug, name) values (22, 25, 'genre-slug-403-irs', 'О бизнесе популярно');
insert into genres (id, parent_id, slug, name) values (23, 25, 'genre-slug-820-und', 'Корпоративная культура');
insert into genres (id, parent_id, slug, name) values (24, 2, 'genre-slug-580-mfv', 'Рыбалка');
insert into genres (id, parent_id, slug, name) values (25, null, 'genre-slug-526-ixp', 'Бизнес-книги');
insert into genres (id, parent_id, slug, name) values (26, 9, 'genre-slug-686-umc', 'Религия и духовная литература');
insert into genres (id, parent_id, slug, name) values (27, 25, 'genre-slug-423-oqc', 'Ценные бумаги / инвестиции');
insert into genres (id, parent_id, slug, name) values (28, 25, 'genre-slug-356-arr', 'Личные финансы');
insert into genres (id, parent_id, slug, name) values (29, 25, 'genre-slug-286-pkr', 'Поиск работы / карьера');
insert into genres (id, parent_id, slug, name) values (30, 25, 'genre-slug-490-ypp', 'Маркетинг, PR, реклама ');
insert into genres (id, parent_id, slug, name) values (31, 2, 'genre-slug-347-mnn', 'Развлечения');
insert into genres (id, parent_id, slug, name) values (32, 25, 'genre-slug-000-hyn', 'Личная эффективность');
insert into genres (id, parent_id, slug, name) values (33, 25, 'genre-slug-401-wud', 'Отраслевые издания');
insert into genres (id, parent_id, slug, name) values (34, 2, 'genre-slug-608-mdn', 'Мода и стиль');
insert into genres (id, parent_id, slug, name) values (35, 2, 'genre-slug-258-gyy', 'Путеводители');
insert into genres (id, parent_id, slug, name) values (36, 25, 'genre-slug-273-eaw', 'Стартапы и создание бизнеса');
insert into genres (id, parent_id, slug, name) values (37, 25, 'genre-slug-536-vav', 'Кадровый менеджмент');
insert into genres (id, parent_id, slug, name) values (38, 16, 'genre-slug-433-jxi', 'Научно-популярная литература');
insert into genres (id, parent_id, slug, name) values (39, 2, 'genre-slug-596-nuz', 'Охота');
insert into genres (id, parent_id, slug, name) values (40, 9, 'genre-slug-748-jup', 'Книги по психологии');
insert into genres (id, parent_id, slug, name) values (41, 25, 'genre-slug-903-nrt', 'Недвижимость');
insert into genres (id, parent_id, slug, name) values (42, 25, 'genre-slug-165-evi', 'Экономика');
insert into genres (id, parent_id, slug, name) values (43, 2, 'genre-slug-304-mgl', 'Хобби / увлечения');
insert into genres (id, parent_id, slug, name) values (44, 2, 'genre-slug-400-hdr', 'Отдых / туризм');
insert into genres (id, parent_id, slug, name) values (45, 25, 'genre-slug-550-jii', 'Логистика');
insert into genres (id, parent_id, slug, name) values (46, 2, 'genre-slug-329-vdq', 'Рукоделие и ремесла');
insert into genres (id, parent_id, slug, name) values (47, 16, 'genre-slug-463-sxp', 'Эзотерика');
insert into genres (id, parent_id, slug, name) values (48, 25, 'genre-slug-145-xxv', 'Финансы');
insert into genres (id, parent_id, slug, name) values (49, 16, 'genre-slug-679-bzd', 'Бизнес-книги');
insert into genres (id, parent_id, slug, name) values (50, 2, 'genre-slug-518-kqq', 'Сделай сам');
insert into genres (id, parent_id, slug, name) values (51, 16, 'genre-slug-152-lfq', 'Изучение языков');
insert into genres (id, parent_id, slug, name) values (52, 16, 'genre-slug-558-qvv', 'Культура и искусство');
insert into genres (id, parent_id, slug, name) values (53, 25, 'genre-slug-693-jyr', 'Делопроизводство');
insert into genres (id, parent_id, slug, name) values (54, 25, 'genre-slug-637-nxa', 'Ораторское искусство / риторика');
insert into genres (id, parent_id, slug, name) values (55, 25, 'genre-slug-584-oka', 'Государственное и муниципальное управление');
insert into genres (id, parent_id, slug, name) values (56, 25, 'genre-slug-444-ehk', 'Малый и средний бизнес');
insert into genres (id, parent_id, slug, name) values (57, 16, 'genre-slug-259-jhl', 'Компьютерная литература');
insert into genres (id, parent_id, slug, name) values (58, 25, 'genre-slug-727-zbu', 'Бухучет / налогообложение / аудит');
insert into genres (id, parent_id, slug, name) values (59, 16, 'genre-slug-126-juq', 'Истории из жизни');
insert into genres (id, parent_id, slug, name) values (60, 16, 'genre-slug-952-aqg', 'Учебная и научная литература');